### ISSUE TITLE
wrong related paper?

### ISSUE THREAD

**Issue by shunsukesaito** [autonomousvision/differentiable_volumetric_rendering#1]
it's very minor but, in other relevant works in ReadMe, should the softras be
Liu et al. - Learning to Infer Implicit Surfaces without 3d Supervision (NeurIPS 2019) instead?

**Comment by m-niemeyer** [comment]
@shunsukesaito yes of cause - sorry, I mixed it up. It should be updated now.

Thanks a lot for pointing this out!
