### ISSUE TITLE
Chamfer distances

### ISSUE THREAD

**Issue by chenhsuanlin** [autonomousvision/differentiable_volumetric_rendering#10]
Hi! I'd like to ask if it'd be possible to provide the Chamfer distance results in Table 1 (2D supervision section) in the uncombined form, i.e. as the accuracy and completeness metrics separately (described in the Occupancy Networks paper)?

Also, a side question, I'm curious why it's called Chamfer-L1, as to my understanding it's not really measured as an L1 norm but rather an unsquared L2 norm.

Thanks in advance!

**Comment by m-niemeyer** [comment]
Hi @chenhsuanlin , thanks for your interest in the project! 

I hope I understood you correctly that you are just interested in the final result tables? If so, you can find the tables you asked for [on page 10 of our supplementary material](http://www.cvlibs.net/publications/Niemeyer2020CVPR_supplementary.pdf). 

Regarding the Chamfer distance, you are right that we use the Euclidean distance for the distance between two points, and then add accuracy and completeness without squaring them. the L1 / L2 is rather referring to the "loss" at the end, so if you take the "l2 loss" (x^2) or the "l1 loss" (abs(x)), and we are taking the l1 loss. 

I hope this helps - good luck with your research!

**Comment by chenhsuanlin** [comment]
Yes this is what I was looking for, I didn't realize it was in the supp material. Thanks!

**Comment by chenhsuanlin** [comment]
Hi @m-niemeyer, I have a quick follow-up question: are the reported chamfer distance numbers scaled?
As I understand, the shapes are normalized to fit unit cubes (between [-0.5,0.5] in xyz), so errors in the order of 0.2 or 0.3 would be extremely large. (I'm guessing it's scaled by 10?)
Thanks!

**Comment by m-niemeyer** [comment]
Hi @chenhsuanlin , yes, you are right - they multiplied by a factor of 10!

We follow previous works here to use "use 1/10 times the maximal edge length of the current object’s bounding box as unit 1" ([see Section 4 - Metrics](http://www.cvlibs.net/publications/Mescheder2019CVPR.pdf)).

**Comment by chenhsuanlin** [comment]
Thanks for the clarification!
