### ISSUE TITLE
How to create the depthmap according to given format

### ISSUE THREAD

**Issue by tharindukn** [autonomousvision/differentiable_volumetric_rendering#16]
Hi! Amazing paper, and very clean code! Thanks so much for releasing this.

I am trying to use multi_view_reconstruction with depth map for 3d reconstruction .I can extract the depth map from the images taken from iphone. i got other necessary informations as well (camera params, images, masks)

![depth_map](https://user-images.githubusercontent.com/13075072/83029014-c9fec900-a04f-11ea-8459-1796d7e3fbe8.JPG)
**deptha map from iphone**

now i need to convert it(depth map - above image) to .exr format.But When i investigate the current .exr files(using affinity designer) at DTU data set there is a channel called "Y" not RGB or A.see below image,

![depthmap](https://user-images.githubusercontent.com/13075072/83036349-1f3ed880-a058-11ea-85ad-3c41cc671622.png)

**Q-1**
Can u guide me how to convert my depth map to the format that need to use for the dvr.

**Q-2**
Also can u share , if there are any prepossessing code to generate the **depth maps**.

**Q-3**
Also can u share , if there are any prepossessing code to generate the **masks**.

**Comment by m-niemeyer** [comment]
Hi @tharinduk90 , thanks a lot for your interest in our project!

**Q-1:** You are able to change to your depth extension using [this config entry](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/configs/default.yaml#L18). The depth maps are then loaded [in this part of the data field](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/im2mesh/data/fields.py#L326). As you can see, we use imageio.imread for this. If you depth format cannot be read by imageio, you can also change this part of the code. 

**Q-2:** You could probably load your depth maps with imageio, and then export them in the exr format.

**Q-3:** No, sorry, we did this manually. But in your case it looks like you could use your depth maps to calculate a mask (there are completely black regions, the depth value might e.g. be 0 / inf here, and then you can convert it into an appropriate binary mask).

I hope this helps a little. Good luck with your project!

**Comment by tharindukn** [comment]
Thank you for the response, 

Is the depth values are in mm ?

**Comment by m-niemeyer** [comment]
Hi @tharinduk90 , The depth values are in line with the [camera projection matrices from the DTU dataset](http://roboimagedata.compute.dtu.dk/?page_id=36). I never checked but I think you are right that the unit of the depth values are mm!

**Comment by tharindukn** [comment]
Hi @m-niemeyer, thank you very much, i was able to identify the issue, in my case depth values and camera projection matrices are not in same units.
