### ISSUE TITLE
Implementation questions

### ISSUE THREAD

**Issue by Kai-46** [autonomousvision/differentiable_volumetric_rendering#17]
Thanks for sharing the great work! I have a silly question regarding the implementation of depth gradient. It seems that the forward procedure of **DepthFunction(torch.autograd.Function**) is explicitly executed by calling **DepthFunction.apply**.  However, I wonder how the backward procedure is called in the codebase. Any help is appreciated! Thanks.

**Comment by m-niemeyer** [comment]
Hi @Kai-46 , thanks for your question.
We define the depth function as our own [autograd](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html) function. This means that you have to define a [forward pass](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/im2mesh/dvr/models/depth_function.py#L303) as well as a [backward pass](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/im2mesh/dvr/models/depth_function.py#L332), and just apply your function - the gradients are then back propagated like for any standard PyTorch autograd function.
[This example from the official PyTorch webpage](https://pytorch.org/tutorials/beginner/examples_autograd/two_layer_net_custom_function.html) might also be helpful.
