### ISSUE TITLE
Training Batch-size and time

### ISSUE THREAD

**Issue by JiejiangWu** [autonomousvision/differentiable_volumetric_rendering#2]
Hi, 
Exciting works and fast open-source!  
A little question: The batch-size is set to 64 in code, and in publication, it's 8. So I want to make sure that is the model trained with 8 x V100 GPU?  Also, could you please tell me about how much time it takes during the whole training? 
Looking forward to your reply. :)

**Comment by m-niemeyer** [comment]
Hi @JiejiangWu , Thanks a lot for your message and interest!

Here an excerpt from our [paper](http://www.cvlibs.net/publications/Niemeyer2020CVPR.pdf): "We train on a single NVIDIA V100GPU with a batch size of 64 images with1024 random pixels each." 

So in the single-view reconstruction experiments, we train with a batch size of 64, and per object, we sample 1024 pixels. We train on a single V100 GPU (we did not perform multi-GPU training). We let the the big models train for quite a long time (2 - 5 weeks). These numbers do not apply to the multi-view reconstruction experiments.

If you want to train on smaller GPUs or with less time, you can use a decoder with a smaller hidden dimension, e.g. 128, by adding
```
model:
  decoder_kwargs:
    hidden_size: 128
```
to your config file. 

I hope this helps. Good luck with your research!

**Comment by JiejiangWu** [comment]
Oh, sorry! I messed up the batch-size in the paper. You are right.
Your reply solves my concerns. I think this issue can be closed.
