### ISSUE TITLE
How to obtain world / camera / scale matrix

### ISSUE THREAD

**Issue by tau-yihouxiang** [autonomousvision/differentiable_volumetric_rendering#24]
Thank you for the provided dataset! However, I don't know how to calculate the provided world / camera / scale matrix. The original dataset set camera mode as "look at" which consists of azimuth, elevation and distance.

**Comment by m-niemeyer** [comment]
Hi @tau-yihouxiang , thanks a lot for your message!

Please have a look at the newly created FAQ: https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/FAQ.md

Thanks a lot!

**Comment by tiexuedanxin** [comment]
> Thank you for the provided dataset! However, I don't know how to calculate the provided world / camera / scale matrix. The original dataset set camera mode as "look at" which consists of azimuth, elevation and distance.

hello, do you know how to obtain world / camera / scale matrix, I want to perform some additional test on  my own dataset to do multiview reconstruction , but I don't know how to create dataset such as how to calculate the world / camera / scale matrix. Could you give me some advice on how to do it, thank you.
