### ISSUE TITLE
How to generate visual_hull_depth ?

### ISSUE THREAD

**Issue by jay-thakur** [autonomousvision/differentiable_volumetric_rendering#25]
Hi,

I have downloaded NMR dataset. i have below image & respective `.exr` file (visual_hull_depth)
![0000](https://user-images.githubusercontent.com/2772085/86245844-b9e68600-bbc7-11ea-9e74-d8b8d0126e47.png)

I am working on my own custom dataset. here is a sample
![0](https://user-images.githubusercontent.com/2772085/86246052-05009900-bbc8-11ea-8e06-1d6243bd5795.png)

Could you please guide me how to create `visual_hull_depth` (.exr file).

Thanks,
Jay

**Comment by m-niemeyer** [comment]
Hi @jay-thakur , thanks a lot for your interest in the project!

The visual hull depth is only used by our model which uses only the RGB Loss: It uses this visual hull depth for the occupancy loss to encourage occupancy along rays where nothing is occupied currently, but where the GT mask suggest it should be occupied. For a more in-depth explanation, [please have a look at the paper](http://www.cvlibs.net/publications/Niemeyer2020CVPR.pdf).

This means that if you use e.g. depth maps, you don't need the visual hull depth. If you want to create them, you need to a.) extract the visual hull, and b.) render it from the respective views to obtain the depth maps. If you don't want to use them during training, you can also disable the use by setting the [config entry data - depth_from_visual_hull](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/75f0507b5f77d48657e7ae0b859626eb2c7b8824/configs/default.yaml#L29) to False.

I hope this helps a little. Good luck with your research!

**Comment by jay-thakur** [comment]
@m-niemeyer Thank you so much.
