### ISSUE TITLE
How to obtain normal, and texture for multi-view reconstruction

### ISSUE THREAD

**Issue by tharindukn** [autonomousvision/differentiable_volumetric_rendering#26]
Hi! Amazing paper, and very clean code! Thanks so much for releasing this.

how to obtain normal map and color map (texture) for multi-view reconstruction ?

**Comment by m-niemeyer** [comment]
Hi @tharinduk90 !

If you have a trained model (you can use one of the pre-trained models as a start), you can [run our generation script](https://github.com/autonomousvision/differentiable_volumetric_rendering#generation) to obtain the output. This will produce a mesh which is textured and has normals (both per vertex). [In this function](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/75f0507b5f77d48657e7ae0b859626eb2c7b8824/im2mesh/dvr/generation.py#L261) we do the per-vertex color prediction, and [here](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/75f0507b5f77d48657e7ae0b859626eb2c7b8824/im2mesh/dvr/generation.py#L287) we do the normal estimation.  If you want to disable the color prediction, you can do this in your config file [modifying the generation - with_normals argument](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/75f0507b5f77d48657e7ae0b859626eb2c7b8824/configs/default.yaml#L87). We do not support any other output format of the normals / texture currently. 

I hope this helps. Good luck!
