### ISSUE TITLE
Generate own dataset

### ISSUE THREAD

**Issue by bell-one** [autonomousvision/differentiable_volumetric_rendering#27]
hello,

I'd like to test your great project with my 3D models like shapenet data you provide
I try to make same structured data with blender but maybe there's something wrong with my codes

how did you generate your training dataset with shapenet models?
can you provide some functions or project to do this?

thank you

**Comment by m-niemeyer** [comment]
Hi @bell-one , thanks for your message!

We prepared the dataset with some internal rendering scripts which are not released. However, as you correctly mentioned, we use the open source software [blender](https://www.blender.org/) for this. If you search a little bit for python blender scripts, there already great projects on this, for example the [stanford-shapenet-renderer](https://github.com/panmari/stanford-shapenet-renderer).

Good luck with your research!
