### ISSUE TITLE
Visualization of the birds scan

### ISSUE THREAD

**Issue by kwea123** [autonomousvision/differentiable_volumetric_rendering#33]
Which code do you use to visualize the 3d bird scan in the readme? I notice that there is specularity and it changes according to the angle. Is it the effect of the rendering program? Because I didn't see any method that deals with specularity prediction or rendering in the paper.

**Comment by m-niemeyer** [comment]
Hi @kwea123 , thanks for your message. In this project, we are concerned with reconstructing textured meshes; our focus does not lie on generating novel views. Hence, you are totally correct that we do not infer view-dependent colors.
The rotations in the readme are renderings of the extracted shape / textured shape. We use the open-source software [blender](https://www.blender.org/) for creating the renderings.

**Comment by kwea123** [comment]
So the lighting effect comes from blender, is that correct?

**Comment by m-niemeyer** [comment]
The view-dependent lighting effects "come from blender", yes
