### ISSUE TITLE
How do you create the object masks in the DTU dataset ?

### ISSUE THREAD

**Issue by phongnhhn92** [autonomousvision/differentiable_volumetric_rendering#36]
![000](https://user-images.githubusercontent.com/11288381/88812928-f99d8f00-d1c0-11ea-9989-a3dd12c15984.png)
Hi,
I am interested in your labeled mask of 3 scans from DTU dataset. I would like to ask how did you label it. My task is to get similar mask for the whole dataset (~100 scenes).

**Comment by m-niemeyer** [comment]
hi @phongnhhn92 , thanks a lot for your interest in our project!

We labelled them ourselves as indicated under [4.2 - Dataset of the main publication](http://www.cvlibs.net/publications/Niemeyer2020CVPR.pdf), so sadly I can't point you to an automatic process for this. We used the [open-source tool Gimp ](https://www.gimp.org/) for creating the object masks.

Good luck with your research!
