### ISSUE TITLE
Error when running training scripts

### ISSUE THREAD

**Issue by MultiPath** [autonomousvision/differentiable_volumetric_rendering#4]
Hi, 

I am interested in your amazing work. I downloaded the datasets with your scripts, and tried to run:

```python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined_pretrained.yaml```

However, it returns errors whatever "configs" I changed as follows:

```
.... (many similar lines)
Error occurred when loading field img of model c61fd3dd6eee6465ccaf38f4d3340ec (04090263)
Error occurred when loading field img of model c9ab6dcc7e4606adf00f0216ab99ff30 (04379243)
Error occurred when loading field img of model c541b8c49b5d2d8e99ad3ba13045dc42 (02691156)
Error occurred when loading field img of model b5d5db47b33a9186ffac3d5f2301b75e (04379243)
Error occurred when loading field img of model bc4db3c90716f7ede76bc197b3a3ffc0 (03636649)
Error occurred when loading field img of model ca063ddc2ea653d7b4b55366da3eebd8 (02958343)
Error occurred when loading field img of model c07c9ca0cfbb531359c956f09c934d51 (04379243)
Error occurred when loading field img of model b47e994452b71943bf30e5b4764cebc0 (03001627)
Error occurred when loading field img of model b6210936b5d1be007670e02527d78e8d (03691459)
Error occurred when loading field img of model c10b1973a0d692ef910979f825490a99 (03001627)
Error occurred when loading field img of model bd28567361a3541d97fb366fa4051f4b (04379243)
Error occurred when loading field img of model bdc5360ff3c62ed69aa9d7f676c1fd7e (02691156)
Error occurred when loading field img of model cb6c20669c6d1dea593ebeeedbff73b (04379243)
Error occurred when loading field img of model bb296502226ae23475becd8a4c3f1866 (03001627)
Error occurred when loading field img of model c695408a86062c4d242ea50288b3f64 (03636649)
Error occurred when loading field img of model b4ae95fbb879bed0ee38cd6552dcaadc (02828884)
Error occurred when loading field img of model ba0c32b3feba49b0b40adee184c371d0 (02958343)
Error occurred when loading field img of model b661b93b67d0ca908cc8e5a741a7e8bd (04379243)
Error occurred when loading field img of model c04d0cf81d9d870a7aa0699f5d30fdef (03001627)
Error occurred when loading field img of model c9b36427b66414de42ca7cc070f21ed3 (04090263)
Error occurred when loading field img of model b431161712ea348cdbbc9440457e303e (03001627)
Traceback (most recent call last):
  File "train.py", line 68, in <module>
    data_viz = next(iter(val_loader))
  File "/private/home/jgu/anaconda3/envs/dvr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/private/home/jgu/anaconda3/envs/dvr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/private/home/jgu/anaconda3/envs/dvr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/private/home/jgu/anaconda3/envs/dvr/lib/python3.8/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/private/home/jgu/anaconda3/envs/dvr/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/private/home/jgu/anaconda3/envs/dvr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/private/home/jgu/data/shapenet/differentiable_volumetric_rendering/im2mesh/data/core.py", line 217, in collate_remove_none
    return data.dataloader.default_collate(batch)
  File "/private/home/jgu/anaconda3/envs/dvr/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 45, in default_collate
    elem = batch[0]
IndexError: list index out of range

Error occurred when loading field img of model c2d6eb0899e5d10dff531859cd52e4b5 (04530566)
Error occurred when loading field img of model bf659a08301f20f2ac94db38cec7b356 (03636649)
```

Have you encountered similar problems before?
Thanks

**Comment by m-niemeyer** [comment]
Hi @MultiPath , thanks a lot for your interest!

Regarding your error, please check the [detailed instructions](https://github.com/autonomousvision/differentiable_volumetric_rendering#generation) where we indicate that the *_pretrained.yaml configs cannot be used for training. Can you try to start training with another config, e.g.

`
python train.py configs/single_view_reconstruction/multi_view_supervision/ours_combined.yaml
`

and check if this works for you? Thanks a lot.

**Comment by MultiPath** [comment]
@m-niemeyer  Thanks for your quick reply!
All the configs showed the same errors on my side. It also reports ```IndexError: list index out of range``` even with ``ours_combined.yaml``

Thanks

**Comment by MultiPath** [comment]
It first shows a lot errors of loading images, while I don't know why this happened:
```
Error occurred when loading field img of model b5ae5354fe7c166319cb07ecb5b4102 (03001627)
Error occurred when loading field img of model b9f28fa7c7181002d436d4e00775800d (02958343)
Error occurred when loading field img of model ca2294ffc664a55afab1bffbdecd7709 (03001627)
Error occurred when loading field img of model c393265168bcc56cf3ced7613d1c130b (04379243)
Error occurred when loading field img of model bb84310d8f022346f2b931201029bc76 (04379243)
Error occurred when loading field img of model bda24b02920f91d1887e8faf8f33b0c5 (03691459)
Error occurred when loading field img of model cf280956401024fe92225eae846f578f (03636649)
Error occurred when loading field img of model c91c78e14fccbab316a2b5862518c93 (04379243)
Error occurred when loading field img of model b23b29f4b08cb2e7b65b71636c46ae49 (04379243)
Error occurred when loading field img of model bd6a8b133fa4d269491d6cee03fef2a9 (03001627)
Error occurred when loading field img of model c627f3639caaf614a6589c01f678d8ea (04379243)
Error occurred when loading field img of model c87497b3c00b3116be8af56c801ecf41 (04256520)
Error occurred when loading field img of model ba673ea75085e46cbfd72d7396bc040a (03001627)
Error occurred when loading field img of model ba97b36204357858e9a890c7dd671d9a (02958343)
Error occurred when loading field img of model b5b6b09711cbee6daa44bfa127abe4bb (02958343)
```

**Comment by m-niemeyer** [comment]
The error messages you show just indicate that it cannot find the dataset. For the configs you tried, it needs the ShapeNet dataset in {your_github_clone}/data/ShapeNet. Can you check if the data is completely downloaded an extracted to this folder? Good luck!

**Comment by MultiPath** [comment]
Hi @m-niemeyer 

I did run your scripts and it showed everything was downloaded and unzipped normally.
To give you a sense, the attached are some screenshots:

![image](https://user-images.githubusercontent.com/5780274/79255959-34b7c480-7e55-11ea-862b-4b8e54656e8d.png)

![image](https://user-images.githubusercontent.com/5780274/79255989-4305e080-7e55-11ea-8284-fabecb337325.png)

All the images were there.

**Comment by MultiPath** [comment]
I was running your ``scripts/download_dataset.sh``

The same error also happened to me for NMR dataset. Both have these errors.

**Comment by m-niemeyer** [comment]
I pulled the repo but I can't reproduce the error.

From your screenshot I can see that the data is in ~/data/shapenet/differentiable_volumetric_rendering/data/ShapeNet. Did you clone the repo to ~/data/shapenet/differentiable_volumetric_rendering?

Please check again that the paths are correct. The data either has to be in {repo_clone}/data/ShapeNet or you can also adjust [the dataset path directly in the config file.](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/configs/default.yaml#L4).
Just to make sure, you can also pull the newest repo (maybe you pulled an earlier version). I will have a look if there is something wrong with the data if still not working.

**Comment by kh9543** [comment]
@MultiPath Can you show the exception caught?
The error seems like coming from this line 
https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/8388d6c1167a2c6de01bc89ffd2c91d6ba930b4c/im2mesh/data/core.py#L164

**Comment by MultiPath** [comment]
Yes. I am sure the codes and paths are correct. I pulled the repo to ~/data/shapenet/differentiable_volumetric_rendering and run the training script under that folder.

Just to make sure if the uploaded datasets are complete or not? 
I am not sure about that, for instance, the downloaded sizes of zip files are:

![image](https://user-images.githubusercontent.com/5780274/79259551-e4436580-7e5a-11ea-8be4-a5072d04db8d.png)

The downloading scripts will automatically unzip the datasets, right?

**Comment by MultiPath** [comment]
> @MultiPath Can you show the exception caught?
> The error seems like coming from this line
> https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/8388d6c1167a2c6de01bc89ffd2c91d6ba930b4c/im2mesh/data/core.py#L164

Thanks @kh9543 

I disabled the "self.no_except" .... and finally got the real Exception now:

![image](https://user-images.githubusercontent.com/5780274/79260031-a2ff8580-7e5b-11ea-82e5-afe57d0415f6.png)

when running for ``ours_combined.yaml``

**Comment by kh9543** [comment]
Ah, I have the same problem.
The error is from depth loading part with imageio.

I solve it by installing freeimage plugin of the imageio module.

**Comment by m-niemeyer** [comment]
I see, you have an error because of imageio. 

I think adding
`
imageio.plugins.freeimage.download()
`
to e.g. train.py (after importing imageio) should fix the problem.

@kh9543, Thanks a lot for your help!

**Comment by MultiPath** [comment]
> I see, you have an error because of imageio.
> 
> I think adding
> `imageio.plugins.freeimage.download()`
> to e.g. train.py (after importing imageio) should fix the problem.
> 
> @kh9543, Thanks a lot for your help!

It works! Thank you very much @m-niemeyer @kh9543  for your kind help!

**Comment by Len-Li** [comment]
I solve this problem by
`conda install -c conda-forge freeimage
`
