### ISSUE TITLE
Multi-view reconstruction on your own images

### ISSUE THREAD

**Issue by Skyfallk** [autonomousvision/differentiable_volumetric_rendering#43]
Hellow, can you advise what config i should use to reconstruct shape form multiple images whithout depth?

**Comment by tharindukn** [comment]
@Skyfallk u can use this => https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/configs/multi_view_reconstruction/angel/ours_rgb.yaml

**Comment by Skyfallk** [comment]
@tharinduk90 thanks, i'll try
