### ISSUE TITLE
Data download link cannot be opened

### ISSUE THREAD

**Issue by diamond0910** [autonomousvision/differentiable_volumetric_rendering#44]
Hi,

can you check why the data download link cannot be opened.

**Comment by m-niemeyer** [comment]
Hi @zhouwy19 , I checked and [the ShapeNet dataset with Choy et. a. renderings](https://s3.eu-central-1.amazonaws.com/avg-projects/differentiable_volumetric_rendering/data/ShapeNet.zip), [the ShapeNet datset with Kato et. al. renderings](https://s3.eu-central-1.amazonaws.com/avg-projects/differentiable_volumetric_rendering/data/NMR_Dataset.zip), and [the DTU dataset](https://s3.eu-central-1.amazonaws.com/avg-projects/differentiable_volumetric_rendering/data/DTU.zip) are online.
