### ISSUE TITLE
Data download link cannot be opened

### ISSUE THREAD

**Issue by diamond0910** [autonomousvision/differentiable_volumetric_rendering#45]
Thank you for your reply

But the links you provided cannot be still opened.  Can you provide other links such as google drive?

Thank you!

**Comment by m-niemeyer** [comment]
Hi @zhouwy19 , I have now checked with several colleagues and for all of them the download links work fine. It is hence caused rather by your connection than our download links. We use the AWS service for providing the data, and we have no other uploads on other platforms, sorry. 

For the download links, please check [your previous issue](https://github.com/autonomousvision/differentiable_volumetric_rendering/issues/44) or our  [download script](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/scripts/download_dataset.sh).
