### ISSUE TITLE
Training for a single class , single image reconstruction 

### ISSUE THREAD

**Issue by trilokpadhi** [autonomousvision/differentiable_volumetric_rendering#47]
Hi 
Thanks for the nice repo !!

I have prepared a dataset for a single class , also written a script to render its views in blender from its corresponding 3d object so I have  image-object pair (approx 900).

Now next can you please tell how to prepare the data to load to the model and train on custom data ?

Thanks

**Comment by m-niemeyer** [comment]
Please have a look at the readme [on how to train a new model](https://github.com/autonomousvision/differentiable_volumetric_rendering#training).

Our data structure has the format:

[ds_folder]
    [class_0]
    [class_1]
    ...
    [class_n]
        [obj_0]
        [0bj_1]
        ...
        [obj_m]

Each "obj_m" folder contains "camera.npz" and the subfolders "image", "mask", "visual_hull_depth" and/or "depth". You can see how the data is loaded and processed in the [main image field](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/ffae3345eb43329c2a20b8f3983ec7b30e1b378e/im2mesh/data/fields.py#L145).

Good luck with your research!
