### ISSUE TITLE
clear on depth back propagation

### ISSUE THREAD

**Issue by hua-wu-que** [autonomousvision/differentiable_volumetric_rendering#5]
Hi!
I try to understand these words from section 3.3 but get very confused:
"In practice, however, we would like to
implement the backward pass not only for a single surface
depth ˆd but for a whole batch of depth values." 

Could you please explain why the backward pass not tackle for a single depth value but for multiple?

Thank you!

**Comment by m-niemeyer** [comment]
Hi @hua-wu-que , thanks for your interest!

Regarding your question, what we mean here is that in a single iteration, we do not only sample a single pixel but a batch of pixels (1024) which we process in parallel. So during the backward pass, we need to handle multiple depth predictions in parallel, where each corresponds to a single pixel. In principle, you are right, we could train with only a single pixel per iteration (and hence a single depth value in the backward pass), but training would be very slow and also very stochastic.

I hope this helps. Good luck with your research!

**Comment by hua-wu-que** [comment]
Thank you for the reply! closing this issue.
