### ISSUE TITLE
Good Results

### ISSUE THREAD

**Issue by ayush9198gupta** [autonomousvision/differentiable_volumetric_rendering#51]
Hi @autonomousvision 

I have used your model and i am having good results but not perfect , like if i am giving simple chair image with horizontal lines so model is generating mesh based on the chair , it is not creating that lines in the mesh.

could you please suggest us to improve the results at best way .

Thanks in advance !!!

**Comment by m-niemeyer** [comment]
Hi @ayush9198gupta , thanks for your interest in the project!

If I understand you correctly, you are performing single-view reconstruction with our model and then you want to obtain better results? One of the main reasons why local details as you mentioned are lost is that we use the encoder-decoder setup with a global code. Results presumably improve when you use local features instead / in addition, e.g. by passing the image through a U-Net type network, and then projecting query points into the source view and pooling local features. If you have multiple views available at test time, you can also train a single model on these views (as we do in our "[multi-view reconstruction experiments](https://github.com/autonomousvision/differentiable_volumetric_rendering/tree/master/configs/multi_view_reconstruction)") which presumably leads to better results.

Good luck with your research!
