### ISSUE TITLE
Output camera projection matrix?

### ISSUE THREAD

**Issue by Kulbear** [autonomousvision/differentiable_volumetric_rendering#53]
Hello,

Thanks for your great work on this problem! I am wondering whether it is also possible  to get the projection matrix that can map the output mesh back to the 2D image?

Thanks!

**Comment by m-niemeyer** [comment]
Hi @Kulbear , thanks for your interest in our project!

We use the [`transform_to_world`](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/ffae3345eb43329c2a20b8f3983ec7b30e1b378e/im2mesh/common.py#L409) function to project pixels with a depth value to the world space. There, you can also find the inverse transform, [`transform_to_camera_space`](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/ffae3345eb43329c2a20b8f3983ec7b30e1b378e/im2mesh/common.py#L454) which is the function which maps 3D world points to the camera space. To get out the final pixel values, you have to divide the first two coordinates by the third which is the depth in camera space. To give an example, we are using the function [here](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/ffae3345eb43329c2a20b8f3983ec7b30e1b378e/im2mesh/dvr/training.py#L250) to get the depth value in camera space.

Good luck with your research!

**Comment by wangsen1312** [comment]
@m-niemeyer Thank you for your great work! 
Can you tell me which configuration can generate the predict camera_mat/world_mat/Scale_mat along with the meshes?
