### ISSUE TITLE
DTU data used in DVR

### ISSUE THREAD

**Issue by rohanchabra** [autonomousvision/differentiable_volumetric_rendering#56]
I wanted to know the reason why you guys used projection_matrices (provided in .txt) and not the calibration file (.mat). The issue is that in my project I want to use the original camera and pose matrices in .mat file and the scale_matrix provided by DVR to normalize the scenes.

**Comment by m-niemeyer** [comment]
Hi @rohanchabra , thanks for your interest in the project. It's true that we use the projection matrices; you can check out the [FAQ](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/FAQ.md) if you want to have a detailed look at how we use the camera instrinsics and extrinsics in our model. If you want to directly decompose the projection matrix from DTU into "[Rt]", you can use[ opencv's deompose function](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#gaaae5a7899faa1ffdf268cd9088940248).

Good luck for your research!
