### ISSUE TITLE
how to train multi-view reconstruction?

### ISSUE THREAD

**Issue by tiexuedanxin** [autonomousvision/differentiable_volumetric_rendering#57]
hello, If i want to train the network by myself to do multi-view reconstruction, like the angle, which .yaml file should i choose? Or should I use ours_depth_mvs_pretrained.yaml, and modify the test model file use the model i trained when do test.thank you very much.

**Comment by m-niemeyer** [comment]
Hi @tiexuedanxin , you can find the config files for the multi-view reconstruction experiments in the [configs/multi_view_reconstruction](https://github.com/autonomousvision/differentiable_volumetric_rendering/tree/master/configs/multi_view_reconstruction) subfolder. If you want to use a pretrained model, you can use the _pretrained config. Have a look at the instructions in the readme for more information. Thanks!

**Comment by tiexuedanxin** [comment]
> Hi @tiexuedanxin , you can find the config files for the multi-view reconstruction experiments in the [configs/multi_view_reconstruction](https://github.com/autonomousvision/differentiable_volumetric_rendering/tree/master/configs/multi_view_reconstruction) subfolder. If you want to use a pretrained model, you can use the _pretrained config. Have a look at the instructions in the readme for more information. Thanks!

hello, I know where there is the config files for the multi-view reconstruction experiments in the configs/multi_view_reconstruction subfolder. and when want to use a pretrained model, can use the _pretrained config. I want to know which config file is your used to train the multi view reconstruction such as the angle、birds, because you say the pretrained config is can't used to train, I don't know if I train a new model of angle、birds use you data which config file to use and how to use the new trained model to generate mesh.  Because I want to do multi view reconstruction, so i want to know which config file to use when train and generate mesh. thank you.
