### ISSUE TITLE
How to prepare data for the model?

### ISSUE THREAD

**Issue by Ethycs** [autonomousvision/differentiable_volumetric_rendering#60]
Hi,

It's not clear to me how to replicate your data format for the training data that comes with the model.
Would you mind providing guidance?

Thanks

**Comment by m-niemeyer** [comment]
Hi @Ethycs , if you use [our download script](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/master/scripts/download_dataset.sh) as indicated [here](https://github.com/autonomousvision/differentiable_volumetric_rendering#download-datasets) in the readme the data is automatically extracted such that you can start training  model.

Good luck with your research!

**Comment by Ethycs** [comment]
@m-niemeyer, allow me to restate:
Can you please provide guidance on preparing other data (such as other models from Shapenet) to be compatible with the Choy and Kato renderings and describe your methodology.

**Comment by Ethycs** [comment]
@m-niemeyer
