### ISSUE TITLE
Is it possible to have a scene-general model for multi-view reconstruction?

### ISSUE THREAD

**Issue by Na-Z** [autonomousvision/differentiable_volumetric_rendering#62]
Hi. Thanks for sharing your awesome work.

I noticed that for the multi-view reconstruction, your method requires to re-train the model for each scene, i.e., scene-specific. I am curious to know if it is possible to make the model scene-general, which means it can reconstruct the scene with multi-view inputs. 

Thanks.

**Comment by m-niemeyer** [comment]
Hi @Na-Z , thanks for your interest in the project!

This is definitely possible, but we haven't explored this in this work. The two most common ways I would see to approach this is to a.) design a multi-view encoder, or b.) perform test-time optimization with multiple views. This, in fact, you could also do with our code where you would basically combine both approaches; first, use the single-view model to obtain a good estimate, and then fine-tune this by optimizing for the given multi-view images.
