### ISSUE TITLE
How to evaluate the chamfer distance for the DTU dataset?

### ISSUE THREAD

**Issue by fomalhautb** [autonomousvision/differentiable_volumetric_rendering#65]
Hi, I noticed that the `eval_mesh.py` only uses `Shapes3dDataset`. If I evaluate the mesh generated by the multi-view model, I get this error:

![image](https://user-images.githubusercontent.com/14837467/135969841-f56f20a0-36d9-4adf-96c3-f0d8cfd21680.png)

How should I evaluate the chamfer distance for the DTU dataset?

**Comment by m-niemeyer** [comment]
Hi @FomalhautB , for the DTU evaluation, we refer to the[ official DTU evaluation scripts](https://roboimagedata.compute.dtu.dk/?page_id=36).
