### ISSUE TITLE
check_ray_intersection_with_unit_cube bottlenecking CPU

### ISSUE THREAD

**Issue by ruoshiliu** [autonomousvision/differentiable_volumetric_rendering#69]
Hi, I was running your code on a custom dataset and I noticed the GPU utilization rate is pretty low due to the method 
[`check_ray_intersection_with_unit_cube`](https://github.com/autonomousvision/differentiable_volumetric_rendering/blob/ffae3345eb43329c2a20b8f3983ec7b30e1b378e/im2mesh/common.py#L112) bottlenecking the CPU. First of all, do you notice this during your experiments? What's a typical GPU utilization rate for you? If this is the case for you as well, I was wondering if setting `use_cube_intersection: false` and using `depth_range` will potentially hurt the model performance? 

Would really appreciate if you can share some insights on this. Thanks in advanced!

**Comment by m-niemeyer** [comment]
Hi @ruoshiliu , yeah we run the above-mentioned on CPU - developing a custom CUDA kernel for this will for sure speed things up quite a bit! If you choose an appropriate depth_range, you can also drop the use_cube_intersection function; we used it such that no tuning of range is required. Best of luck for your research !

**Comment by ruoshiliu** [comment]
That makes sense. Thank you for your suggestion!
